# -*- mode: ruby -*-
# vi: set ft=ruby :

  ### Master Node ####

Vagrant.configure("2") do |config|
  config.vm.define "mine-control1" do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "kube-control1"
    config.vm.network "private_network", ip: "192.168.56.47"
    config.vm.network "forwarded_port", guest: 22, host: 60047, auto_correct: true, id: "ssh"  #호스트 60047로 접속시 가상머신 22번으로  포트포워딩
    config.vm.provision "shell", path: "config.sh"
    config.vm.provision "shell", path: "install.sh"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "mine-control1"
      vb.cpus = 2
      vb.memory = 3072
      if !File.exist?("disk00.vdi")
        vb.customize ["createmedium", "disk", "--filename", "disk00.vdi", "--size", 10240]
      end
      vb.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", 2, "--device", 0, "--type", "hdd", "--medium", "disk00.vdi"]
    end
  end
end